### ISSUE TITLE
error on authentication

### ISSUE THREAD

**Issue by skyrina** [RichardDorian/node-character.ai#2]
trying to use the character.ai api with the example script, i get an error. the access token i've provided is correct.
seems that cloudflare is filtering this library's requests out.
```
undefined:1
error code: 1020
^

SyntaxError: Unexpected token 'e', "error code: 1020" is not valid JSON
    at JSON.parse (<anonymous>)
    at CharacterAI.<anonymous> (/home/user/source/spamton/dist/Client.js:63:43)
    at step (/home/user/source/spamton/dist/Client.js:44:23)
    at Object.next (/home/user/source/spamton/dist/Client.js:25:53)
    at fulfilled (/home/user/source/spamton/dist/Client.js:16:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.2.0
```

**Comment by sum117** [comment]
We are aware of the issue and will try to fix this ASAP. 

It has to do with a recent update on their backend, even our insomnia requests are failing.
